package com.pet.stock_price_tracker.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_IS_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    EXPIRED_TOKEN,
    AUTHORIZATION_HEADER_IS_MISSING,
    INTEGRATION_REQUEST_ERROR,
    INVALID_CHARACTERS
}
