-- liquibase formatted sql

-- changeset wladw:1738612245386-1
CREATE TABLE roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    user_id   BIGINT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- changeset wladw:1738612245386-2
ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

