-- liquibase formatted sql

-- changeset wladw:1737233454726-3
CREATE TABLE tickers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    open    numeric,
    close   numeric,
    highest numeric,
    lowest  numeric,
    date    date,
    ticker  VARCHAR                                 NOT NULL,
    CONSTRAINT tickers_pk PRIMARY KEY (id)
);