-- liquibase formatted sql

-- changeset wladw:1738612292575-1
CREATE TABLE permissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_type VARCHAR(255),
    role_id         BIGINT,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- changeset wladw:1738612292575-2
ALTER TABLE permissions
    ADD CONSTRAINT FK_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id)

